//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_parts_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetails
    {
        public int SalesDetailID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> PartID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual AutoParts AutoParts { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
